
services:
  web:
    build:
      context: .
      target: development
    restart: unless-stopped
    container_name: nawaat_nextjs_dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /home/husam/Pictures/nawaat-uploads:/app/public/uploads:rw
    environment:
      - WATCHPACK_POLLING=true 
    env_file:
      - .env.development
    networks:
      - nawaat_net
    # depends_on:
    #   postgres:
    #     condition: service_healthy 
    #   rabbitmq:
    #     condition: service_healthy 
    command: sh -c "npx prisma generate && npm run dev"

  postgres:
    image: postgres:15
    container_name: nawaat_postgres_dev
    restart: unless-stopped
    env_file:
      - .env.development
    ports:
      - "5430:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nawaat_net

    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U admin -d evo"]
    #   interval: 5s
    #   timeout: 5s
    #   retries: 5


  rabbitmq:
    image: rabbitmq:3-management
    container_name: nawaat_rabbitmq_dev
    hostname: nawaat-rabbit
    restart: unless-stopped
    env_file:
      - .env.development
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - nawaat_net
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    # healthcheck:
    #   test: rabbitmq-diagnostics -q ping
    #   interval: 5s
    #   timeout: 5s
    #   retries: 5

  meilisearch:
    image: getmeili/meilisearch:v1.9
    container_name: nawaat_meilisearch_dev
    restart: unless-stopped
    env_file:
      - .env.development
    environment:
      - MEILI_MASTER_KEY=nawaat-meili-dev-key-2024
      - MEILI_NO_ANALYTICS=true
    ports:
      - "7700:7700"
    volumes:
      - meilisearch_data:/meili_data
    networks:
      - nawaat_net

volumes:
  postgres_data:
    name: nawaat_postgres_data_dev
  rabbitmq_data:
    name: nawaat_rabbitmq_data_dev
  meilisearch_data:
    name: nawaat_meilisearch_data_dev



networks:
  nawaat_net:
    name: nawaat_network_dev
    external: true
    
